openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: http://localhost:5000/api/
info:
  version: "1.0.0"
  title: Recipe Book
  description: SoftUni project
paths:
  /user/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: API to register new users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User(Register)'
      responses:
        '200':
          description: Created - User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User(RegisterDetails)'
        '500':
          description: Bad Request - Invalid request body or user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User Already Exists
  /user/login:
    post:
      tags:
        - Auth
      summary: Login user
      description: API to authenticate and login users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User(Login)'
      responses:
        '200':
          description: OK - User successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User(LoginDetails)'
        '500':
          description: Bad Request - Invalid request body or user already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid Credentials
  /user/logout:
    get:
      summary: Logout User
      description: API for logging out users and clearing refresh token from cookies
      tags:
        - Auth
      responses:
        '204':
          description: No Content - Successfully logged out
        '500':
          description: Internal Server Error - No refresh token found in cookies
  /category:
    get:
      summary: Retrieve all categories
      description: This API manages movie categories within the application.
      tags:
        - Category
      responses:
        '200':
          description: A list of all categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category(Details)'
        '500':
          description: Internal Server Error - Something went wrong
    post:
      summary: Create a new category
      description: This API manages movie categories within the application.
      tags:
        - Category
      security:
        - bearerAuth: [] 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                name: Gluten-Free
      responses:
        '200':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category(Details)'
        '500':
          description: Internal Server Error - Something went wrong
  /category/{categoryId}:
    get:
      summary: Get a category by ID
      description: This API manages movie categories within the application.
      tags:
        - Category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
          description: ID of the category to get.
      responses:
        '200':
          description: Category found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category(Details)'
        '500':
          description: Internal Server Error - This id is not valid or not Found
    put:
      summary: Update a category by ID
      description: This API manages movies categories within the application.
      tags:
        - Category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
          description: ID of the category to update.
      security:
        - bearerAuth: [] 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category(Create,Update)'
      responses:
        '200':
          description: Updated category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category(Details)'
        '500':
          description: Internal Server Error - This id is not valid or not Found
    delete:
      summary: Delete a category by ID
      description: This API manages movie categories within the application.
      tags:
        - Category
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
          description: ID of the category to delete.
      security:
        - bearerAuth: []    
      responses:
        '200':
          description: Deleted category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category(Details)'
        '500':
          description: Internal Server Error - This id is not valid or not Found
  /recipe:
    get:
      summary: Get all recipes
      description: Retrieve a list of all recipes, with optional query parameters for filtering, sorting, and pagination.
      tags:
        - Recipe
      responses:
        '200':
          description: A list of recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe(Details)'
        '500':
          description: Internal Server Error
    post:
      summary: Create a new recipe
      description: Create a new recipe with the provided details. Requires authentication.
      tags:
        - Recipe
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe(Create,Update)'
      responses:
        '200':
          description: The created recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe(Details)'
        '500':
          description: Internal Server Error - There is no token attached to header
  /recipe/{id}:
    get:
      summary: Get a recipe by ID
      description: Retrieve a recipe by its ID.
      tags:
        - Recipe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The recipe ID
      responses:
        '200':
          description: The recipe details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe(Details)'
        '500':
          description: Internal Server Error
    put:
      summary: Update a recipe by ID
      description: Update a recipe with the provided details by its ID. Requires authentication.
      tags:
        - Recipe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The recipe ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recipe(Create,Update)'
      responses:
        '200':
          description: The updated recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe(Details)'
        '500':
          description: Internal Server Error - This id is not valid or not Found
    delete:
      summary: Delete a recipe by ID
      description: Delete a recipe by its ID. Requires authentication.
      tags:
        - Recipe
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The recipe ID
      responses:
        '200':
          description: The deleted recipe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe(Details)'
        '500':
          description: Internal Server Error - This id is not valid or not Found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Category(Create,Update):
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The name of the category
          unique: true
          index: true
          required: true
      example:
        name: "Gluten-Free"
    Category(Details):
      type: object
      required:
        - name
      properties:
        _id:
          type: string
          description: Automatically generated. The unique identifier for the object.
        name:
          type: string
          description: The name of the category
          unique: true
          index: true
          required: true
        createdAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the category was created.
        updatedAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the category was last updated.
      example:
        _id: "6716b5e535521560572f28cc"
        name: "Test Category"
        createdAt: "2024-10-21T20:13:25.395Z"
        updatedAt: "2024-10-21T20:13:25.395Z"
    Recipe(Create,Update):
      type: object
      required:
        - title
        - ingredients
        - instructions
        - cookingTime
        - servings
        - category
      properties:
        _id:
          type: string
          description: Automatically generated. The unique identifier for the Recipe.
        title:
          type: string
          description: The title of the recipe
          example: Spaghetti Carbonara
          required: true
        description:
          type: string
          description: A short description of the recipe
          example: A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the ingredient
                example: Spaghetti
                required: true
              quantity:
                type: string
                description: The quantity of the ingredient
                example: 200g
                required: true
        instructions:
          type: array
          items:
            type: object
            properties:
              step:
                type: string
                description: The instruction step
                example: Cook the spaghetti according to package instructions.
                required: true
        cookingTime:
          type: number
          description: The cooking time in minutes
          example: 20
          required: true
        servings:
          type: number
          description: The number of servings
          example: 2
          required: true
        category:
          type: string
          description: Reference to the category's _id
          required: true
      example:
        title: Test Food
        description: "Test Description"
        ingredients:
          - name: Spaghetti
            quantity: 200g
        instructions:
          - step: Cook the according to package instructions.
        cookingTime: 20
        servings: 2
        category: 123abc
    Recipe(Details):
      type: object
      required:
        - title
        - ingredients
        - instructions
        - cookingTime
        - servings
        - category
      properties:
        _id:
          type: string
          description: Automatically generated. The unique identifier for the Recipe.
        title:
          type: string
          description: The title of the recipe
          example: Spaghetti Carbonara
          required: true
        description:
          type: string
          description: A short description of the recipe
          example: A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.
        ingredients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the ingredient
                example: Spaghetti
                required: true
              quantity:
                type: string
                description: The quantity of the ingredient
                example: 200g
                required: true
        instructions:
          type: array
          items:
            type: object
            properties:
              step:
                type: string
                description: The instruction step
                example: Cook the spaghetti according to package instructions.
                required: true
        cookingTime:
          type: number
          description: The cooking time in minutes
          example: 20
          required: true
        servings:
          type: number
          description: The number of servings
          example: 2
          required: true
        category:
          $ref: '#/components/schemas/Category(Details)'
        createdAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the recipe was created
        updatedAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the recipe was last updated
      example:
        title: Test Food
        description: "Test Description"
        ingredients:
          - name: Spaghetti
            quantity: 200g
        instructions:
          - step: Cook the according to package instructions.
        cookingTime: 20
        servings: 2
        category: 
          _id: "6716b5e535521560572f28cc"
          name: "Test Category"
          createdAt: "2024-10-21T20:13:25.395Z"
          updatedAt: "2024-10-21T20:13:25.395Z"
    User(Register):
      type: object
      required:
        - firstname
        - lastname
        - email
        - password
      properties:
        firstname:
          type: string
          description: The first name of the user
          required: true
        lastname:
          type: string
          description: The last name of the user
          required: true
        email:
          type: string
          description: The email address of the user
          unique: true
          required: true
        password:
          type: string
          description: The password of the user
          required: true
      example:
        firstname: "John"
        lastname: "Doe"
        email: "john.doe@example.com"
        password: "password123"
    User(Login):
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: The email address of the user
          unique: true
          required: true
        password:
          type: string
          description: The password of the user
          required: true
      example:
        email: "john.doe@example.com"
        password: "password123"
    User(RegisterDetails):
      type: object
      required:
        - firstname
        - lastname
        - email
      properties:
        _id:
          type: string
          description: Automatically generated. The unique identifier for the object.
        firstname:
          type: string
          description: The first name of the user
          required: true
        lastname:
          type: string
          description: The last name of the user
          required: true
        email:
          type: string
          description: The email address of the user
          unique: true
          required: true
        createdAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the object was created
        updatedAt:
          type: string
          format: date-time
          description: Automatically generated. The date and time when the object was last updated
      example:
        _id: "6716b5e535521560572f28cc"
        firstname: "John"
        lastname: "Doe"
        email: "john.doe@example.com"
        createdAt: "2024-10-21T20:13:25.395Z"
        updatedAt: "2024-10-21T20:13:25.395Z"
    User(LoginDetails):
      type: object
      required:
        - firstname
        - lastname
        - email
      properties:
        _id:
          type: string
          description: Automatically generated. The unique identifier for the object
        firstname:
          type: string
          description: The first name of the user
          required: true
        lastname:
          type: string
          description: The last name of the user
          required: true
        email:
          type: string
          description: The email address of the user
          unique: true
          required: true
        token:
          type: string
          description: The JWT token for the authenticated user
          example: "eyJhbGciOiJIUzI1NiIsIn..."
      example:
        _id: "6716b5e535521560572f28cc"
        firstname: "John"
        lastname: "Doe"
        email: "john.doe@example.com"
        token: "eyJhbGciOiJIUzI1NiIsIn..."